#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

import string

def is_unreadable(s):
    for i, c in enumerate(s):
        if i % 2 == 0 and c in string.ascii_lowercase:
            continue
        if i % 2 == 1 and c in string.ascii_uppercase:
            continue
        return False
    return True

# def solve(S: str) -> str:
def solve(S):
    if is_unreadable(S):
        return YES
    else:
        return NO

# generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)

if __name__ == '__main__':
    main()
