#!/usr/bin/env python3
# from typing import *



# def solve(X: int) -> int:
def solve(X):
    return 100 - (X % 100)

# generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
def main():
    X = int(input())
    a = solve(X)
    print(a)

if __name__ == '__main__':
    main()
