#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(auto N, auto M, auto X, auto Y, const vector<auto> & A, const vector<auto> & B, const vector<auto> & T, const vector<auto> & K) {
    // TODO: edit here
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    constexpr char endl = '\n';
    auto N, M, X, Y;
    cin >> N >> M;
    vector<auto> A(M), B(M), T(M), K(M);
    cin >> X >> Y;
    REP (i, M) {
        cin >> A[i] >> B[i] >> T[i] >> K[i];
    }
    auto ans = solve(N, M, X, Y, A, B, T, K);
    cout << ans << endl;
    return 0;
}
