#!/usr/bin/env python3
# from typing import *

def g1(n):
    return int(''.join(reversed(sorted(str(n)))))

def g2(n):
    return int(''.join(sorted(str(n))))

def f(n):
    return g1(n) - g2(n)

# def solve(N: int, K: int) -> int:
def solve(N, K):
    for i in range(K):
        N = f(N)
    return N

# generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    a = solve(N, K)
    print(a)

if __name__ == '__main__':
    main()
